<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <title>Laporan Kartu Keluarga</title>

    <style>
        @page { margin: 28px 32px; }

        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 11px;
            color: #0f172a;
        }

        .header {
            border-bottom: 4px solid #10b981;
            padding-bottom: 14px;
            margin-bottom: 18px;
        }

        .brand {
            font-size: 11px;
            color: #059669;
            font-weight: bold;
            text-transform: uppercase;
            letter-spacing: 1px;
        }

        .title {
            margin: 4px 0 0;
            font-size: 22px;
            font-weight: bold;
            color: #064e3b;
        }

        .subtitle {
            margin-top: 4px;
            color: #64748b;
        }

        .summary {
            width: 100%;
            margin: 18px 0;
            border-spacing: 8px;
        }

        .summary td {
            background: #ecfdf5;
            border: 1px solid #bbf7d0;
            padding: 12px;
        }

        .summary-label {
            font-size: 9px;
            color: #64748b;
            font-weight: bold;
            text-transform: uppercase;
        }

        .summary-value {
            margin-top: 4px;
            font-size: 18px;
            font-weight: bold;
            color: #047857;
        }

        table.data {
            width: 100%;
            border-collapse: collapse;
        }

        table.data th {
            background: #064e3b;
            color: white;
            padding: 9px 7px;
            font-size: 9px;
            text-align: left;
            text-transform: uppercase;
        }

        table.data td {
            border-bottom: 1px solid #e2e8f0;
            padding: 8px 7px;
        }

        table.data tr:nth-child(even) {
            background: #f8fafc;
        }

        .badge {
            background: #dcfce7;
            color: #047857;
            padding: 3px 8px;
            font-size: 9px;
            font-weight: bold;
            border-radius: 999px;
        }

        .footer {
            position: fixed;
            bottom: -10px;
            left: 0;
            right: 0;
            font-size: 9px;
            color: #64748b;
            border-top: 1px solid #e2e8f0;
            padding-top: 8px;
        }

        .footer-left { float: left; }
        .footer-right { float: right; }
    </style>
</head>

<body>
    <div class="header">
        <div class="brand">Aplikasi Manajemen Data Desa</div>
        <h1 class="title">Laporan Kartu Keluarga</h1>
        <div class="subtitle">Rekapitulasi data kartu keluarga desa.</div>
        <div class="subtitle">Dicetak pada: {{ now()->format('d-m-Y H:i') }}</div>
    </div>

    <table class="summary">
        <tr>
            <td>
                <div class="summary-label">Total KK</div>
                <div class="summary-value">{{ $kartuKeluargas->count() }}</div>
            </td>
            <td>
                <div class="summary-label">KK Aktif</div>
                <div class="summary-value">{{ $kartuKeluargas->where('status', 'Aktif')->count() }}</div>
            </td>
            <td>
                <div class="summary-label">Dusun Terdata</div>
                <div class="summary-value">{{ $kartuKeluargas->pluck('dusun')->filter()->unique()->count() }}</div>
            </td>
            <td>
                <div class="summary-label">RW Terdata</div>
                <div class="summary-value">{{ $kartuKeluargas->pluck('rw')->filter()->unique()->count() }}</div>
            </td>
        </tr>
    </table>

    <table class="data">
        <thead>
            <tr>
                <th>No</th>
                <th>No KK</th>
                <th>Kepala Keluarga</th>
                <th>Dusun</th>
                <th>Blok</th>
                <th>RT</th>
                <th>RW</th>
                <th>Status</th>
            </tr>
        </thead>

        <tbody>
            @foreach ($kartuKeluargas as $kk)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $kk->no_kk }}</td>
                    <td><strong>{{ $kk->kepala_keluarga }}</strong></td>
                    <td>{{ $kk->dusun ?? '-' }}</td>
                    <td>{{ $kk->blok ?? '-' }}</td>
                    <td>{{ $kk->rt ?? '-' }}</td>
                    <td>{{ $kk->rw ?? '-' }}</td>
                    <td><span class="badge">{{ $kk->status }}</span></td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <div class="footer-left">Laporan Kartu Keluarga Desa</div>
        <div class="footer-right">Generated by Desa Digital</div>
    </div>
</body>
</html>