<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8">
    <title>Laporan Surat</title>

    <style>
        @page { margin: 28px 32px; }

        body {
            font-family: DejaVu Sans, sans-serif;
            font-size: 11px;
            color: #0f172a;
        }

        .header {
            border-bottom: 4px solid #06b6d4;
            padding-bottom: 14px;
            margin-bottom: 18px;
        }

        .brand {
            font-size: 11px;
            color: #0891b2;
            font-weight: bold;
            text-transform: uppercase;
            letter-spacing: 1px;
        }

        .title {
            margin: 4px 0 0;
            font-size: 22px;
            font-weight: bold;
            color: #164e63;
        }

        .subtitle {
            margin-top: 4px;
            color: #64748b;
        }

        .summary {
            width: 100%;
            margin: 18px 0;
            border-spacing: 8px;
        }

        .summary td {
            background: #ecfeff;
            border: 1px solid #a5f3fc;
            padding: 12px;
        }

        .summary-label {
            font-size: 9px;
            color: #64748b;
            font-weight: bold;
            text-transform: uppercase;
        }

        .summary-value {
            margin-top: 4px;
            font-size: 18px;
            font-weight: bold;
            color: #0891b2;
        }

        table.data {
            width: 100%;
            border-collapse: collapse;
        }

        table.data th {
            background: #164e63;
            color: white;
            padding: 9px 7px;
            font-size: 9px;
            text-align: left;
            text-transform: uppercase;
        }

        table.data td {
            border-bottom: 1px solid #e2e8f0;
            padding: 8px 7px;
            vertical-align: top;
        }

        table.data tr:nth-child(even) {
            background: #f8fafc;
        }

        .badge {
            padding: 3px 8px;
            font-size: 9px;
            font-weight: bold;
            border-radius: 999px;
            background: #cffafe;
            color: #0e7490;
        }

        .footer {
            position: fixed;
            bottom: -10px;
            left: 0;
            right: 0;
            font-size: 9px;
            color: #64748b;
            border-top: 1px solid #e2e8f0;
            padding-top: 8px;
        }

        .footer-left { float: left; }
        .footer-right { float: right; }
    </style>
</head>

<body>
    <div class="header">
        <div class="brand">Aplikasi Manajemen Data Desa</div>
        <h1 class="title">Laporan Surat Menyurat</h1>
        <div class="subtitle">Rekapitulasi data administrasi surat desa.</div>
        <div class="subtitle">Dicetak pada: {{ now()->format('d-m-Y H:i') }}</div>
    </div>

    <table class="summary">
        <tr>
            <td>
                <div class="summary-label">Total Surat</div>
                <div class="summary-value">{{ $surats->count() }}</div>
            </td>
            <td>
                <div class="summary-label">Diajukan</div>
                <div class="summary-value">{{ $surats->where('status', 'Diajukan')->count() }}</div>
            </td>
            <td>
                <div class="summary-label">Diproses</div>
                <div class="summary-value">{{ $surats->where('status', 'Diproses')->count() }}</div>
            </td>
            <td>
                <div class="summary-label">Selesai</div>
                <div class="summary-value">{{ $surats->where('status', 'Selesai')->count() }}</div>
            </td>
        </tr>
    </table>

    <table class="data">
        <thead>
            <tr>
                <th>No</th>
                <th>Nomor Surat</th>
                <th>Jenis Surat</th>
                <th>Pemohon</th>
                <th>NIK</th>
                <th>Tanggal</th>
                <th>Status</th>
            </tr>
        </thead>

        <tbody>
            @foreach ($surats as $surat)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $surat->nomor_surat }}</td>
                    <td><strong>{{ $surat->jenis_surat }}</strong></td>
                    <td>{{ $surat->penduduk?->nama ?? '-' }}</td>
                    <td>{{ $surat->penduduk?->nik ?? '-' }}</td>
                    <td>{{ $surat->tanggal_surat ?? '-' }}</td>
                    <td><span class="badge">{{ $surat->status }}</span></td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <div class="footer-left">Laporan Surat Desa</div>
        <div class="footer-right">Generated by Desa Digital</div>
    </div>
</body>
</html>